version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - "15432:5432"
    hostname: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      options:
        max-size: 5m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -d
        - ${DB_NAME}
        - -U
        - ${DB_USER}
      interval: 2s
      timeout: 3s
      retries: 40
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
    command: sh -c "alembic upgrade head && fastapi run app/main.py --port 8000"
volumes:
  db-data: {}